### ISSUE TITLE
Assertion 'dst_p == byte_code_p + initializers_length' failed in parser_post_processing

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/jerryscript#1389]
Version: 9915307
OS: Linux-4.4.0-38-generic-x86_64-with-debian-stretch-sid

Load the attached test with debug jerry:

``` js
function x(){}[280,1045,523,613,892,802,722,357,766,843,1015,624,260,418,a5,261,376,306(n("o")).a,583,585,586,587,569,589,466,533,745,1012,633,809,368,1245,513,607,g='r',516("",'c'),981,tf(f(b()))=z instanceof 636,758,1004,782,661,455,839,801,630([]=c),bg[0],634,637,638,1099,644,645,294,635,987,650,259('t'),514,290,658,967,725,710,662,667,668,989,672,326,673,343,679(ab(-0)+886),436,739(a="te"),375,826,485,690,785[872],446,904['u',"V",824],704,705,706,593,[](.4),711,304,687,507,723,666,321,497,911,317,730,966,292,500,591,818,a1(nc).s,740,746,747,748,749,363,520,820,333,685,827,831,834,286,693,403,840,841,288,367,392,848,881,592,695,887,912,890,258,893,894,828,273,400,462,808,b8,285,h,856,868,385,913,914,915,916,303,465,919,920,921,922,415,924,391,b4,632,930,931,932,933,934,935,957,331,871,515,w,e,o,627,732,955,677,947,1024,508,501,394,961,'e',296,964,973,c9,cl.l,289,975(y("M")),977,310,979,652,884,473,983,554,988,270,640,991,293,691,962,703,287((cn(t))=u),"f",448,1006,665,788,470,698,1017,855,1020,1021];{}l(i.p(564)=r)
```

Output:

```
ICE: Assertion 'dst_p == byte_code_p + initializers_length' failed at jerryscript/jerry-core/parser/js/js-parser.c(parser_post_processing):1532.
Error: ERR_FAILED_INTERNAL_ASSERTION
Aborted
```

Backtrace:

```
ICE: Assertion 'dst_p == byte_code_p + initializers_length' failed at jerryscript/jerry-core/parser/js/js-parser.c(parser_post_processing):1532.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0x00000000005c57c8 in raise ()
#0  0x00000000005c57c8 in raise ()
#1  0x00000000005c597a in abort ()
#2  0x000000000057d175 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/targets/default/jerry-port-default-fatal.c:54
#3  jerry_fatal (code=code@entry=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:62
#4  0x000000000057d350 in jerry_assert_fail (assertion=assertion@entry=0x66c2c8 "dst_p == byte_code_p + initializers_length", file=file@entry=0x66bdd8 "jerryscript/jerry-core/parser/js/js-parser.c", function=function@entry=0x66c830 <__func__.5725> "parser_post_processing", line=line@entry=1532) at jerryscript/jerry-core/jrt/jrt-fatals.c:86
#5  0x0000000000585479 in parser_post_processing (context_p=context_p@entry=0x7fffffffcb40) at jerryscript/jerry-core/parser/js/js-parser.c:1532
#6  0x000000000058b82e in parser_parse_source.lto_priv.207 (source_p=<optimized out>, size=<optimized out>, strict_mode=<optimized out>, error_location_p=0x7fffffffcd90) at jerryscript/jerry-core/parser/js/js-parser.c:1887
#7  0x0000000000403d59 in parser_parse_script (bytecode_data_p=<synthetic pointer>, is_strict=false, size=<optimized out>, source_p=<optimized out>) at jerryscript/jerry-core/parser/js/js-parser.c:2248
#8  jerry_parse (is_strict=false, source_size=<optimized out>, source_p=<optimized out>) at jerryscript/jerry-core/jerry.c:284
#9  main (argc=<optimized out>, argv=<optimized out>) at jerryscript/jerry-main/main-unix.c:409
```

**Comment by akosthekiss** [comment]
Fixed in #1410
